//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhoThuocTay
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class khothuoctayEntities : DbContext
    {
        public khothuoctayEntities()
            : base("name=khothuoctayEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<loaithuoc> loaithuocs { get; set; }
        public virtual DbSet<thuoc> thuocs { get; set; }
        public virtual DbSet<view_loaithuoc> view_loaithuoc { get; set; }
        public virtual DbSet<view_thuoc> view_thuoc { get; set; }
    }
}
