//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhoThuocTay
{
    using System;
    using System.Collections.Generic;
    
    public partial class thuoc
    {
        public int mathuoc { get; set; }
        public string tenthuoc { get; set; }
        public string noisanxuat { get; set; }
        public System.DateTime ngaysanxuat { get; set; }
        public System.DateTime hansudung { get; set; }
        public int maloaithuoc { get; set; }
        public string nhacungcap { get; set; }
        public int soluong { get; set; }
        public int dongia { get; set; }
        public string donvitinh { get; set; }
    
        public virtual loaithuoc loaithuoc { get; set; }
    }
}
