//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhoThuocTay
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_loaithuoc
    {
        public Nullable<long> sothutu { get; set; }
        public int maloaithuoc { get; set; }
        public string tenloaithuoc { get; set; }
    }
}
